In [ ]:
import numpy as np

# Task 1: Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))

# Task 2: Initialize an all-ones array with size 4X2
ones_array = np.ones((4, 2))

# Task 3: Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 5)  # Example: 3x3 array filled with 5

# Task 4: Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)

# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)

# Task 6: Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

# Printing the results
print("Task 1: Empty array (2x2):")
print(empty_array)

print("\nTask 2: All ones array (4x2):")
print(ones_array)

print("\nTask 3: Array filled with value (5):")
print(fill_value_array)

print("\nTask 4: Array of zeros with same shape and type as given array:")
print(zeros_like_array)

print("\nTask 5: Array of ones with same shape and type as given array:")
print(ones_like_array)

print("\nTask 6: Converted numpy array from list:")
print(numpy_array)


Task 1: Empty array (2x2):
[[0. 0.]
 [0. 0.]]

Task 2: All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Task 3: Array filled with value (5):
[[5 5 5]
 [5 5 5]
 [5 5 5]]

Task 4: Array of zeros with same shape and type as given array:
[[0 0]
 [0 0]]

Task 5: Array of ones with same shape and type as given array:
[[1 1]
 [1 1]]

Task 6: Converted numpy array from list:
[1 2 3 4]


In [35]:
import numpy as np;
# 1 Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
array= np.arange(10,50)
print("\narray from 10 to 49 = ",array)
# 2 Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
matrix= np.arange(9).reshape(3,3);
print("\n3*3 matrix from 0 to 8")
print(matrix);

#3 Create 3*3 identity matrix
identity_matrix=np.eye(3);
print("\n3*3 identity matrix")
print(identity_matrix);

#Create a random array of size 30 and find the mean of the array.
#{Hint:check for np.random.random() and array.mean() function}
random_array=np.random.random(30);
print("\nrandom array of size 30")
print(random_array);
mean_value = random_array.mean();
print("\nmean value of the array is ",mean_value);

#Create a 10X10 array with random values and find the minimum and maximum values.4
ten_array= np.random.random((10,10))
print("\n 10*10 array = ",ten_array)
min_value = ten_array.min();
max_value = ten_array.max();
print("\nthe minimun value = ",min_value);
print("\nthe maximim value = ",max_value);

#Create a zero array of size 10 and replace 5th element with 1.
zero_array =np.zeros(10);
print("\n zero array before modification = ",zero_array);
zero_array[4]=1;
print("\n zero array after modification = ",zero_array);

#reverse an array
rev_array=[1,2,0,0,4,0];
rev=rev_array[::-1]
print("array = ",rev_array);
print("the reverse of array = ",rev)

#Create a 2d array with 1 on border and 0 inside.
D_array= np.ones((5,5));
D_array[1:-1, 1:-1] = 0;
print("\n 2D array : ")
print(D_array);

checkerboard = np.zeros((8, 8))

# Fill the matrix with the checkerboard pattern
checkerboard[::2, ::2] = 1  # Set 1's on even rows and even columns
checkerboard[1::2, 1::2] = 1  # Set 1's on odd rows and odd columns
print("\n checkboard pattern :")
print(checkerboard)


array from 10 to 49 =  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3*3 matrix from 0 to 8
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3*3 identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

random array of size 30
[0.49634788 0.33878993 0.19591985 0.89140226 0.51997174 0.63862135
 0.44502442 0.21751762 0.67116424 0.29063839 0.92416395 0.91271403
 0.56244039 0.26442709 0.73574444 0.27284315 0.8873172  0.02646982
 0.58206857 0.12701121 0.15841835 0.10738299 0.97601808 0.39305798
 0.04468583 0.29278837 0.72468952 0.15469094 0.52439287 0.40343573]

mean value of the array is  0.4593386052734681

 10*10 array =  [[0.88826353 0.19680896 0.57034468 0.30977086 0.32645904 0.57474487
  0.17804563 0.42368208 0.50647728 0.61080992]
 [0.71019475 0.30054877 0.58262669 0.91926198 0.74538018 0.86804138
  0.34064736 0.83899429 0.75012313 0.36872571]
 [0.80709088 0.16062491 0.39411184 0.05133994 0.94217976 0.86598391
  0.04568072 0.5822

In [49]:
#adding two array
x= np.array([[1,2],[3,5]])
y= np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])
add=x+y;
print("the addition of x and y is ");
print(add);
#subutraction
sub=x-y;
print("the subtraction of x and y is");
print(sub);
#finding the square of each element of the array
squ=np.square(x);
print("\n square of the element x :");
print(squ);
#finding the dot product
dot_product =np.dot(v,w);
dot_product2 =np.dot(x,v);
dot_product3 =np.dot(x,y);
print("\n the dot product of v and w = ",dot_product);
print("\n the dot product of x and v = ",dot_product2);
print("\n the dot product of x and y = ",dot_product3);
#concatinate x and y
concat_xy_row = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along rows:")
print(concat_xy_row)

concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenate v and w along columns:")
print(concat_vw_col)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenate x and v along rows:")
    print(concat_xv)
except Exception as e:
    print("Error:", e)
'''we will get an error here because x is a 2x2 matrix and v is a 1D array.
 To concatenate along axis 0 or 1, the shapes must match.
  for concatenation along axis 0, the number of columns in both arrays
   should match, and for axis 1, the number of rows should match.'''

the addition of x and y is 
[[ 6  8]
 [10 13]]
the subtraction of x and y is
[[-4 -4]
 [-4 -3]]

 square of the element x :
[[ 1  4]
 [ 9 25]]

 the dot product of v and w =  219

 the dot product of x and v =  [29 77]

 the dot product of x and y =  [[19 22]
 [50 58]]

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [50]:
import numpy as np

# Given Arrays A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I (Identity Matrix)
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 = \n", identity_matrix)

# 2. Prove AB != BA (Matrix multiplication is not commutative)
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print("BA = \n", BA)

# 3. Prove (AB)^T = B^T * A^T (Transpose property)
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
B_T_A_T = np.dot(B_T, A_T)
print("(AB)^T = \n", AB_T)
print("B^T * A^T = \n", B_T_A_T)

# 4. Solve the system of linear equations using Inverse Method
# The system is:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Define matrix A (coefficients) and matrix B (constants)
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve using inverse method (A^-1 * B)
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("Solution using Inverse Method (x, y, z):")
print(X)  # This will give us [x, y, z]

# 5. Solve using np.linalg.inv (already solved in previous step)
# The np.linalg.inv function is already used to find the inverse and solve for X


A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
(AB)^T = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]
Solution using Inverse Method (x, y, z):
[ 2.  1. -2.]


In [51]:
import time
import numpy as np

# Create matrices of size 1000x1000
size = 1000
matrix1_list = [[1 for _ in range(size)] for _ in range(size)]
matrix2_list = [[2 for _ in range(size)] for _ in range(size)]
matrix1_array = np.ones((size, size))
matrix2_array = np.full((size, size), 2)

# Matrix multiplication using Python lists
start_time = time.time()
result_list = [[sum(a * b for a, b in zip(row_a, col_b))
                for col_b in zip(*matrix2_list)] for row_a in matrix1_list]
end_time = time.time()
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Matrix multiplication using NumPy arrays
start_time = time.time()
result_array = np.dot(matrix1_array, matrix2_array)
end_time = time.time()
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")

Time taken using Python lists: 124.01562905311584 seconds
Time taken using NumPy arrays: 0.06900453567504883 seconds
